---
title: "Schedule"
description: |
  Below is the official schedule for the event. All times are in EDT.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Opening Remarks

Time: 9:45-10:00

Speaker: Luis Sierra Muntané (SGSU President)



### Block 1: Data Science Theory</span>  

Chair:  (UofT DoSS)

| Time          | Title                                                                 | Speaker                      |
|---------------------|-----------------------------------------------------------------------|------------------------------|
| 10:00–10:30   | *Convergence and Optimality of the EM Algorithm Under Multi-Component Gaussian Mixture Models* [(abstract)](abstracts.html#bingqing-li) | Bingqing Li (UofT DoSS)      |
| 10:30–11:00   | *Sparsity Meets Low-Rank: A Stein-Based Framework for Unbiased Risk Estimation in Matrix Denoising* [(abstract)](abstracts.html#luis-sierra-muntane) | Luis Sierra Muntané (UofT DoSS)           |





### Block 2: Applied Statistics</span>  

Chair: Pat Chimtanoo (UofT DoSS)

| Time          | Title                                                                 | Speaker                             |
|--------------------|-----------------------------------------------------------------------|-------------------------------------|
| 11:15–11:45   | *Scalable Gaussian Process Inference via Deep Generative Models: A New Framework for High-Cadence Time Series* [(abstract)](abstracts.html#rodrigo-herrera) | Rodrigo Herrera (UofT DoSS)                    |
| 11:45–12:15   | *Hierarchical Bayesian Copula Model for Probabilistic Population Projection* [(abstract)](abstracts.html#yichen-ji) | Yichen Ji (UofT DoSS)              |
| 12:15–12:45   | *A Spatiotemporal Analysis of Extreme Fire Weather in British Columbia: Identifying a Structural Change Point from 1981 to 2023* [(abstract)](abstracts.html#zoya-zaman) | Zoya Zaman (UGuelph) |


### Lunch

Time: 12:45–13:30



### Block 3: Mathematical Finance and Actuarial Science</span>  

Chair: Elijah French (UofT DoSS)

| Time          | Title                                                                 | Speaker                          |
|--------------------|-----------------------------------------------------------------------|----------------------------------|
| 13:30–14:00   | *Adaptive Window Selection for Financial Risk Forecasting* [(abstract)](abstracts.html#chenxin-lyu) | Chenxin Lyu (UWaterloo Stats)       |
| 14:00–14:30   | *Dynamic Pareto Optima in Multi-Period Pure-Exchange Economies* [(abstract)](abstracts.html#brandon-tam) | Brandon Tam (UofT DoSS)              |


### Poster Session

Time: 14:30–15:45

Abstracts for the poster session are also available [here](abstracts.html#Poster-Presentation).




### Block 4: Machine Learning</span>  

Chair: KC Tsiolis (UofT DoSS)

| Time          | Title                                                                 | Speaker                          |
|--------------------|-----------------------------------------------------------------------|----------------------------------|
| 15:45–16:15   | *A Pragmatic Method for Comparing Clusterings with Overlaps and Outliers* [(abstract)](abstracts.html#ryan-dewolfe) | Ryan DeWolfe (TMU Mathematics)              |
| 16:15–16:45   | *Sequential Probability Assignment against Smoothed Adversaries with Unknown Base Measure* [(abstract)](abstracts.html#ziyi-liu) | Ziyi Liu (UofT DoSS)         |


### Closing Remarks

Time: 16:45-17:00

Speaker: Luis Sierra Muntané (SGSU President)













